### ISSUE TITLE
Possible to run on CPU device?

### ISSUE THREAD

**Issue by spacerunner8** [Taeu/Style-Your-Hair#1] opened 2022-07-25 09:10 UTC
Hello

Thank you for sharing, the results seem very promising.

I ran the code on my CPU device unfortunately it does not work even I set `--device = "cpu"`. I found out it is because it relies on `fused_bias_act.cpp` and `fused_bias_act_kernel.cu` and they rely on CUDA.

In this case, do you think we can only use CPU to generate results?

**Comment by myoons** [comment] 2022-07-27 17:44
The problem is fixed now. Can you try again with the latest code? (Reflecting the newest commit, https://github.com/Taeu/Style-Your-Hair/pull/2#issue-1319847083)

I tested the code with my Macbook M1 Pro which PyTorch doesn't support GPU.

**Comment by myoons** [comment] 2022-08-18 06:26
Issue closed. 😄  Thanks for having interests.

**Comment by myoons** [comment] 2022-08-18 06:27
Issue closed. 😄 Thanks for having interests.

**Closed by myoons** 2022-08-18 06:27 UTC

**Comment by ArsalanAli915** [comment] 2023-10-18 08:13
@myoons @Taeu could u please specify the inference time that model has taken. Becouse it takes around 18 mins to inference on GPU T4 google colab. Can I cut the time short. Please help me know.
